In [9]:
# problem statement ---> What is the risk for given data?
# speed=160 km/h, car_age=10 years, experience= 5 years

"""
Y= MX+C
risk = M1*speed + M2*car_age + M3*experience + intercept

"""

'\nY= MX+C\nrisk = M1*speed + M2*car_age + M3*experience + intercept\n\n'

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [11]:
df=pd.read_csv("/kaggle/input/datasets/rkhademul19/car-data/car data.csv")
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

In [12]:
# fill up the null value using mean or median

exp_fit=df.experience.median()
exp_fit

5.0

In [13]:
# fillna() funtion to fill the null data

df.experience= df.experience.fillna(exp_fit)
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

In [14]:
# Apply Linear Regression
from sklearn.linear_model import LinearRegression
reg= LinearRegression()

In [15]:
# model train
reg.fit(df[['speed','car_age','experience']],df.risk)

LinearRegression()

In [17]:
#  risk of the given data

reg.predict([[160,10,5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([71.37146872])

In [18]:
reg.coef_

array([ 0.33059217,  1.61053246, -6.20772074])

In [19]:
reg.intercept_

np.float64(33.41000091043588)

In [20]:
# manually calculation
# Y= MX+C
# risk = M1*speed + M2*car_age + M3*experience + intercept
0.33059217*160+ 1.61053246*10 + 5* -6.20772074 + 33.41000091043588

71.37146901043589