In [1]:
# problem statement ---> What is the risk for given data?
# speed=160 km/h, car_age=10 years, experience= 5 years

"""
Y= MX+C
risk = M1*speed + M2*car_age + M3*experience + intercept

"""

'\nY= MX+C\nrisk = M1*speed + M2*car_age + M3*experience + intercept\n'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [3]:
df=pd.read_csv("/kaggle/input/datasets/rkhademul19/car-data/car data.csv")
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

In [7]:
# fill up the null value using mean or median

exp_fit=df.experience.median()
exp_fit

5.0

In [10]:
# fillna() funtion to fill the null data

df.experience= df.experience.fillna(exp_fit)
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10